[platformio]
src_dir = .
data_dir = data

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
build_flags = 
    -O2
    -D CORE_DEBUG_LEVEL=0
lib_deps = 
    links2004/WebSockets @ ^2.6.1
    bblanchon/ArduinoJson @ ^6.21.3
